const db = require('../connection');
const rows=(sql,params=[])=>db.prepare(sql).all(...params); const row=(sql,params=[])=>db.prepare(sql).get(...params);
const changes=(sql,params=[])=>Number(db.prepare(sql).run(...params).changes);
const getGlobalScratchcardStats=async()=>row("SELECT * FROM GlobalGameStats WHERE gameId='scratchcards'")||{gameId:'scratchcards',totalPlayed:0,totalWins:0,totalPayout:0};
async function createScratchcard(userId,packId,grid,winAmount){const result=db.prepare('INSERT INTO Scratchcards (userId,type,grid,winAmount) VALUES (?,?,?,?)').run(userId,String(packId),JSON.stringify(grid),winAmount);return{id:Number(result.lastInsertRowid),userId,packId,grid,winAmount,status:'purchased'};}
async function purchaseScratchcardTransaction(userId,packId,packName,price,grid,winAmount){db.exec('BEGIN IMMEDIATE');try{const user=row('SELECT koala_balance FROM Users WHERE id=?',[userId]);if(!user||user.koala_balance<price)throw new Error('Insufficient balance or user not found');changes('UPDATE Users SET koala_balance=koala_balance-? WHERE id=?',[price,userId]);changes("UPDATE GlobalGameStats SET totalPlayed=totalPlayed+1 WHERE gameId='scratchcards'");const result=db.prepare("INSERT INTO Scratchcards (userId,type,grid,winAmount,status,price) VALUES (?,?,?,?,'purchased',?)").run(userId,String(packId),JSON.stringify(grid),winAmount,price);const id=Number(result.lastInsertRowid);db.prepare('INSERT INTO KoalaTransactions (user_id,amount,reason) VALUES (?,?,?)').run(userId,-price,`Purchased Scratchcard: ${packName} (ID: ${id})`);db.exec('COMMIT');return{id,grid,winAmount};}catch(error){db.exec('ROLLBACK');throw error;}}
const getScratchcard=async(id)=>row('SELECT * FROM Scratchcards WHERE id=?',[id]);
const getUserPurchasedScratchcard=async(userId)=>row("SELECT * FROM Scratchcards WHERE userId=? AND status='purchased' ORDER BY createdAt DESC LIMIT 1",[userId]);
async function claimScratchcard(id,userId){db.exec('BEGIN IMMEDIATE');try{const card=row('SELECT winAmount,status,price FROM Scratchcards WHERE id=? AND userId=?',[id,userId]);if(!card)throw new Error('Scratchcard not found');if(card.status!=='purchased')throw new Error('Scratchcard already claimed or invalid');changes("UPDATE Scratchcards SET status='claimed' WHERE id=?",[id]);if(card.winAmount>0){changes('UPDATE Users SET koala_balance=koala_balance+? WHERE id=?',[card.winAmount,userId]);db.prepare('INSERT INTO KoalaTransactions (user_id,amount,reason) VALUES (?,?,?)').run(userId,card.winAmount,`Scratchcard Win (ID: ${id})`);changes("UPDATE GlobalGameStats SET totalPayout=totalPayout+?,totalWins=totalWins+1 WHERE gameId='scratchcards'",[card.winAmount]);}db.exec('COMMIT');return{success:true,winAmount:card.winAmount,price:card.price};}catch(error){db.exec('ROLLBACK');throw error;}}
const getScratchcardPools=async()=>rows('SELECT * FROM ScratchcardPools');
const addScratchcardPoolTeam=async(cardType,teamCode)=>changes('INSERT OR IGNORE INTO ScratchcardPools (card_type,team_code) VALUES (?,?)',[cardType,teamCode]);
const removeScratchcardPoolTeam=async(cardType,teamCode)=>changes('DELETE FROM ScratchcardPools WHERE card_type=? AND team_code=?',[cardType,teamCode]);
const getScratchcardConfigs=async()=>rows('SELECT * FROM ScratchcardConfigs');
const updateScratchcardConfig=async(cardType,price,winChance,rewardAmount)=>changes('INSERT INTO ScratchcardConfigs (card_type,price,win_chance,reward_amount) VALUES (?,?,?,?) ON CONFLICT(card_type) DO UPDATE SET price=excluded.price,win_chance=excluded.win_chance,reward_amount=excluded.reward_amount',[cardType,price,winChance,rewardAmount]);
const getLatestScratchcardWinners=async(limit=10)=>rows(`SELECT s.id,s.winAmount,s.createdAt,u.displayName,u.username,u.preferences,s.type AS packId FROM Scratchcards s JOIN Users u ON s.userId=u.id WHERE s.status='claimed' AND s.winAmount>0 ORDER BY s.createdAt DESC LIMIT ?`,[limit]);
const getTopScratchcardWinners=async(limit=10)=>rows(`SELECT SUM(s.winAmount) AS totalWon,COUNT(s.id) AS winCount,u.displayName,u.username,u.preferences FROM Scratchcards s JOIN Users u ON s.userId=u.id WHERE s.status='claimed' AND s.winAmount>0 GROUP BY u.id ORDER BY totalWon DESC LIMIT ?`,[limit]);
const getScratchcardLeaderboard=async()=>rows(`SELECT u.displayName,u.username,u.preferences,SUM(s.winAmount) AS totalWon,COUNT(s.id) AS totalBought,SUM(CASE WHEN s.winAmount>0 THEN 1 ELSE 0 END) AS ticketsWon FROM Scratchcards s JOIN Users u ON s.userId=u.id WHERE s.status='claimed' GROUP BY u.id ORDER BY totalWon DESC LIMIT 10`);
const getScratchcardLeaderboardData=async(limit=10)=>rows(`SELECT u.id AS userId,u.displayName,u.username,u.preferences,SUM(s.winAmount) AS totalWon,COUNT(s.id) AS ticketsClaimed,SUM(CASE WHEN s.winAmount>0 THEN 1 ELSE 0 END) AS wins FROM Scratchcards s JOIN Users u ON s.userId=u.id WHERE s.status='claimed' GROUP BY u.id ORDER BY totalWon DESC LIMIT ?`,[limit]);
const getScratchcardChartData=async(limit=14)=>rows("SELECT date(createdAt) AS day,SUM(winAmount) AS dailyWin FROM Scratchcards WHERE status='claimed' GROUP BY day ORDER BY day DESC LIMIT ?",[limit]).reverse();
const getScratchcardPacks=async()=>rows('SELECT * FROM scratchcard_packs ORDER BY created_at DESC'); const getScratchcardPack=async(id)=>row('SELECT * FROM scratchcard_packs WHERE id=?',[id]);
async function createScratchcardPack(pack){const{name,region_label,scope,price,win_chance,reward_amount,is_weighted,max_daily_limit,is_active,is_special}=pack;const result=db.prepare('INSERT INTO scratchcard_packs (name,region_label,scope,price,win_chance,reward_amount,is_weighted,max_daily_limit,is_active,is_special) VALUES (?,?,?,?,?,?,?,?,?,?)').run(name,region_label,scope,price,win_chance||0.3,reward_amount||0,is_weighted?1:0,max_daily_limit||0,is_active?1:0,is_special?1:0);return{id:Number(result.lastInsertRowid),...pack};}
async function updateScratchcardPack(id,pack){const{name,region_label,scope,price,win_chance,reward_amount,is_weighted,max_daily_limit,is_active,is_special}=pack;return changes('UPDATE scratchcard_packs SET name=?,region_label=?,scope=?,price=?,win_chance=?,reward_amount=?,is_weighted=?,max_daily_limit=?,is_active=?,is_special=? WHERE id=?',[name,region_label,scope,price,win_chance,reward_amount,is_weighted?1:0,max_daily_limit||0,is_active?1:0,is_special?1:0,id]);}
const deleteScratchcardPack=async(id)=>changes('DELETE FROM scratchcard_packs WHERE id=?',[id]); const getScratchcardPackTeams=async(packId)=>rows('SELECT * FROM scratchcard_pack_teams WHERE pack_id=? ORDER BY position ASC',[packId]);
async function setScratchcardPackTeams(packId,teamCodes){db.exec('BEGIN IMMEDIATE');try{changes('DELETE FROM scratchcard_pack_teams WHERE pack_id=?',[packId]);const statement=db.prepare('INSERT INTO scratchcard_pack_teams (pack_id,team_code,position) VALUES (?,?,?)');teamCodes.forEach((code,index)=>statement.run(packId,code,index));db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}}
const getUserDailyPackCount=async(userId,packId)=>row('SELECT COUNT(*) AS count FROM Scratchcards WHERE userId=? AND type=? AND date(createdAt)=date(?)',[userId,String(packId),new Date().toISOString().split('T')[0]]).count;
module.exports={getGlobalScratchcardStats,createScratchcard,purchaseScratchcardTransaction,getScratchcard,getUserPurchasedScratchcard,claimScratchcard,getScratchcardPools,addScratchcardPoolTeam,removeScratchcardPoolTeam,getScratchcardConfigs,updateScratchcardConfig,getLatestScratchcardWinners,getTopScratchcardWinners,getScratchcardLeaderboard,getScratchcardLeaderboardData,getScratchcardChartData,getScratchcardPacks,getScratchcardPack,createScratchcardPack,updateScratchcardPack,deleteScratchcardPack,getScratchcardPackTeams,setScratchcardPackTeams,getUserDailyPackCount};
